-- Guest & Godparent Tracker
-- Run this entire script in Supabase > SQL Editor.

create table if not exists public.guests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  family_name text not null default '',
  guest_name text not null,
  phone text not null default '',
  email text not null default '',
  invited_count integer not null default 1 check (invited_count >= 1),
  rsvp text not null default 'Pending' check (rsvp in ('Pending','Attending','Declined')),
  attendance text not null default 'Not checked' check (attendance in ('Not checked','Attended','Absent')),
  notes text not null default ''
);

create table if not exists public.godparents (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null,
  role text not null default '',
  phone text not null default '',
  confirmation text not null default 'Pending' check (confirmation in ('Pending','Confirmed','Declined')),
  payment_status text not null default 'Unpaid' check (payment_status in ('Unpaid','Partial','Paid','Not required')),
  payment_amount numeric(12,2) not null default 0 check (payment_amount >= 0),
  notes text not null default ''
);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists guests_updated_at on public.guests;
create trigger guests_updated_at before update on public.guests
for each row execute function public.set_updated_at();

drop trigger if exists godparents_updated_at on public.godparents;
create trigger godparents_updated_at before update on public.godparents
for each row execute function public.set_updated_at();

alter table public.guests enable row level security;
alter table public.godparents enable row level security;

-- IMPORTANT:
-- This app intentionally has NO LOGIN. These policies make the data readable/writable
-- by anyone who has access to the published app. Do not store sensitive information.
drop policy if exists "public guests read" on public.guests;
drop policy if exists "public guests insert" on public.guests;
drop policy if exists "public guests update" on public.guests;
drop policy if exists "public guests delete" on public.guests;

create policy "public guests read" on public.guests for select using (true);
create policy "public guests insert" on public.guests for insert with check (true);
create policy "public guests update" on public.guests for update using (true) with check (true);
create policy "public guests delete" on public.guests for delete using (true);

drop policy if exists "public godparents read" on public.godparents;
drop policy if exists "public godparents insert" on public.godparents;
drop policy if exists "public godparents update" on public.godparents;
drop policy if exists "public godparents delete" on public.godparents;

create policy "public godparents read" on public.godparents for select using (true);
create policy "public godparents insert" on public.godparents for insert with check (true);
create policy "public godparents update" on public.godparents for update using (true) with check (true);
create policy "public godparents delete" on public.godparents for delete using (true);

-- Optional demo rows. Delete these after testing if desired.
-- insert into public.guests (family_name, guest_name, invited_count) values ('Sample Family','Juan Dela Cruz',2);
-- insert into public.godparents (name, role) values ('Sample Godparent','Ninong');
